### ISSUE TITLE
5" version

### ISSUE THREAD

**Issue by MrFr1day** [usausa/turing-smart-screen#3]
Hi,

I've a 5" version of this monitor, which uses UsbMonitor**L**, but it does not use the same protocol as the 3.5" (I've tested your library and mathoudebine's Python library, for both revision A and B), is there anyway to add support for it?

Main differences:
- Resolution is 800x480.
- Onboard memory (10MB).
- SD Card port.
- The ability to view onboard/SD Card album photos/play Videos, or use them as background.
- The Monitor it self renders the transparency of the elements on top of the background.

Official link (turzx.com) for the monitor resources:
https://lgb123-1253504678.cos.ap-beijing.myqcloud.com/5inchENG.rar

Thanks.

**Comment by usausa** [comment]
I can add support if the protocol is analized, but currently it is difficult for me to analize.

**Comment by MrFr1day** [comment]
Hi,

I've analyzed their protocol and posted it [here](https://github.com/mathoudebine/turing-smart-screen-python/issues/90) with a working example code (although it's in Python), please review it and consider adding support for the 5" in your library.

Thanks.

**Comment by TheBlueGreen** [comment]
> Hi,
> 
> I've a 5" version of this monitor, which uses UsbMonitor**L**, but it does not use the same protocol as the 3.5" (I've tested your library and mathoudebine's Python library, for both revision A and B), is there anyway to add support for it?
> 
> Main differences:
> 
> * Resolution is 800x480.
> * Onboard memory (10MB).
> * SD Card port.
> * The ability to view onboard/SD Card album photos/play Videos, or use them as background.
> * The Monitor it self renders the transparency of the elements on top of the background.
> 
> Official link (turzx.com) for the monitor resources: https://lgb123-1253504678.cos.ap-beijing.myqcloud.com/5inchENG.rar
> 
> Thanks.

This is off topic but could you please upload the "5inchENG.rar" somewhere for me to download it? I just recieved this screen and the official link is offline. Thank you!

**Comment by MrFr1day** [comment]
@TheBlueGreen

This is their current edition, dated 2022/12/13:

https://easyupload.io/n7c9ae

**Comment by jovantehno** [comment]
any updates for 5" turzx?

**Comment by ErikApption** [comment]
I did have a look at their USBMonitorL but sadly they did obfuscate the code and was not able to locate the serial protocol - but @MrFr1day serial protocol analysis should be a good start... Although I'm guessing this 5" unit looks more powerful/complicated than its previous verison.

**Comment by usausa** [comment]
Merged 5" support.
https://github.com/usausa/turing-smart-screen/pull/5

Released version 2.2.0.
https://www.nuget.org/packages/TuringSmartScreenLib
